title: The very first GitHub Pages
author: Laverden
email: nlav05@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tutorial introducing to GitHub Pages. Nothing fancy, just a self-improvement
  exercise.
theme: minima
# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  Laverden # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
